version: "3.7"
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      - 'MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT}'
    volumes:
      - 'mariadb-data:/var/lib/mysql'

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - 'SHELL=/bin/bash'
    working_dir: /home/frappe
    volumes:
      - './workspace:/workspace'

volumes:
  mariadb-data:
